google.maps.__gjsload__('geometry', function(_){var Lla=function(a,b){return Math.abs(_.rl(b-a,-180,180))},Mla=function(a,b,c,d,e){if(!d){c=Lla(a.lng(),c)/Lla(a.lng(),b.lng());if(!e)return e=Math.sin(_.xk(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.xk(b.lat())),_.yk(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.Nn(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.xk(a.lat());a=_.xk(a.lng());d=_.xk(b.lat());b=_.xk(b.lng());c=_.xk(c);return _.rl(_.yk(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},Nla=function(a,b){a=new _.om(a,!1);b=new _.om(b,!1);return a.equals(b)},Ola=function(a,b,c){a=_.um(a);c=c||1E-9;const d=_.rl(a.lng(),-180,180),e=b instanceof _.Cv,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(let r=0,u=g.getLength();r<u;++r){const w=g.getAt(r),x=w.getLength(),y=e?x:x-1;for(let D=0;D<y;++D){var h=w.getAt(D);const I=w.getAt((D+
1)%x);if(Nla(h,a)||Nla(I,a))return!0;var l=_.rl(h.lng(),-180,180),n=_.rl(I.lng(),-180,180);const L=Math.max(l,n),K=Math.min(l,n);if(l=Math.abs(_.rl(l-n,-180,180))<=1E-9&&(Math.abs(_.rl(l-d,-180,180))<=c||Math.abs(_.rl(n-d,-180,180))<=c)){l=a.lat();n=Math.min(h.lat(),I.lat())-c;var p=Math.max(h.lat(),I.lat())+c;l=l>=n&&l<=p}if(l)return!0;if(L-K>180?d+c>=L||d-c<=K:d+c>=K&&d-c<=L)if(h=Mla(h,I,d,f,b),Math.abs(h-a.lat())<c)return!0}}return!1},Pla=function(a,b){const c=_.qm(a);a=_.rm(a);const d=_.qm(b);
b=_.rm(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))},Qla=function(a,b,c){a=_.um(a);b=_.um(b);c=c||6378137;return Pla(a,b)*c},Tla=function(a,b){b=b||6378137;a instanceof _.Ho&&(a=a.getArray());a=(0,_.Ft)(a);if(a.length===0)return 0;const c=Array(4),d=Array(3),e=[1,0,0,0],f=Array(3);Rla(a[a.length-1],f);for(let w=0;w<a.length;++w)Rla(a[w],d),tE(f,d,c),Sla(c,e,e),[f[0],f[1],f[2]]=d;const [g,h,l]=f,[n,p,r,u]=e;return 2*Math.atan2(g*
p+h*r+l*u,n)*(b*b)},Ula=function(a,b){if(isFinite(a)){var c=a%360;a=Math.round(c/90);c-=a*90;if(c===30||c===-30){c=Math.sign(c)*.5;var d=Math.sqrt(.75)}else c===45||c===-45?(c=Math.sign(c)*Math.SQRT1_2,d=Math.SQRT1_2):(d=c/180*Math.PI,c=Math.sin(d),d=Math.cos(d));switch(a&3){case 0:b[0]=c;b[1]=d;break;case 1:b[0]=d;b[1]=-c;break;case 2:b[0]=-c;b[1]=-d;break;default:b[0]=-d,b[1]=c}}else b[0]=NaN,b[1]=NaN},Rla=function(a,b){const c=Array(2);Ula(a.lat(),c);const [d,e]=c;Ula(a.lng(),c);const [f,g]=c;
b[0]=e*g;b[1]=e*f;b[2]=d},Sla=function(a,b,c){const d=a[0]*b[1]+a[1]*b[0]+a[2]*b[3]-a[3]*b[2],e=a[0]*b[2]-a[1]*b[3]+a[2]*b[0]+a[3]*b[1],f=a[0]*b[3]+a[1]*b[2]-a[2]*b[1]+a[3]*b[0];c[0]=a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3];c[1]=d;c[2]=e;c[3]=f},tE=function(a,b,c){var d=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2];const g=a[0]+b[0],h=a[1]+b[1],l=a[2]+b[2];var n=g*g+h*h+l*l,p=e*l-f*h;f=f*g-d*l;d=d*h-e*g;e=n*n+p*p+f*f+d*d;if(e!==0)b=Math.sqrt(e),c[0]=n/b,c[1]=p/b,c[2]=f/b,c[3]=d/b;else{a:for(n=[a[0]-b[0],a[1]-
b[1],a[2]-b[2]],p=0;p<3;++p)if(n[p]!==0){if(n[p]<0){n=[-n[0],-n[1],-n[2]];break a}break}p=0;for(f=1;f<n.length;++f)Math.abs(n[f])<Math.abs(n[p])&&(p=f);f=[0,0,0];f[p]=1;n=[n[1]*f[2]-n[2]*f[1],n[2]*f[0]-n[0]*f[2],n[0]*f[1]-n[1]*f[0]];p=Math.hypot(...n);n=[n[0]/p,n[1]/p,n[2]/p];p=Array(4);tE(a,n,p);a=Array(4);tE(n,b,a);Sla(a,p,c)}},uE=class{};uE.isLocationOnEdge=Ola;
uE.containsLocation=function(a,b){a=_.um(a);const c=_.rl(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs");var f=b.get("map");f=!d&&f?f.getProjection():null;let g=!1;for(let l=0,n=e.getLength();l<n;++l){const p=e.getAt(l);for(let r=0,u=p.getLength();r<u;++r){const w=p.getAt(r),x=p.getAt((r+1)%u);var h=_.rl(w.lng(),-180,180);const y=_.rl(x.lng(),-180,180),D=Math.max(h,y);h=Math.min(h,y);(D-h>180?c>=D||c<h:c<D&&c>=h)&&Mla(w,x,c,d,f)<a.lat()&&(g=!g)}}return g||Ola(a,b)};var vE=class{};vE.computeSignedArea=Tla;
vE.computeArea=function(a,b){if(!(a instanceof _.Ho||Array.isArray(a)||a instanceof _.un||a instanceof _.Oo))try{a=_.tn(a)}catch(c){try{a=new _.Oo((0,_.is)(a))}catch(d){throw _.Ul("Invalid path passed to computeArea(): "+JSON.stringify(a));}}b=b||6378137;if(a instanceof _.Oo){if(a.getRadius()===void 0)throw _.Ul("Invalid path passed to computeArea(): Circle is missing radius.");if(a.getRadius()<0)throw _.Ul("Invalid path passed to computeArea(): Circle must have non-negative radius.");if(b<0)throw _.Ul("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");
if(a.getRadius()>Math.PI*b)throw _.Ul("Invalid path passed to computeArea(): Circle must not cover more than 100% of the sphere.");return 2*Math.PI*b**2*(1-Math.cos(a.getRadius()/b))}if(a instanceof _.un){if(b<0)throw _.Ul("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");if(a.ni.lo>a.ni.hi)throw _.Ul("Invalid path passed to computeArea(): the southern LatLng of a LatLngBounds cannot be more north than the northern LatLng.");let c=2*Math.PI*b**2*(1-Math.cos((a.ni.lo-
90)*Math.PI/180));c-=2*Math.PI*b**2*(1-Math.cos((a.ni.hi-90)*Math.PI/180));return c*Math.abs(a.Mh.hi-a.Mh.lo)/360}return Math.abs(Tla(a,b))};vE.computeLength=function(a,b){b=b||6378137;let c=0;a instanceof _.Ho&&(a=a.getArray());for(let d=0,e=a.length-1;d<e;++d)c+=Qla(a[d],a[d+1],b);return c};vE.computeDistanceBetween=Qla;
vE.interpolate=function(a,b,c){a=_.um(a);b=_.um(b);const d=_.qm(a);var e=_.rm(a);const f=_.qm(b),g=_.rm(b),h=Math.cos(d),l=Math.cos(f);b=Pla(a,b);const n=Math.sin(b);if(n<1E-6)return new _.om(a.lat(),a.lng());a=Math.sin((1-c)*b)/n;c=Math.sin(c*b)/n;b=a*h*Math.cos(e)+c*l*Math.cos(g);e=a*h*Math.sin(e)+c*l*Math.sin(g);return new _.om(_.yk(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.yk(Math.atan2(e,b)))};
vE.computeOffsetOrigin=function(a,b,c,d){a=_.um(a);c=_.xk(c);b/=d||6378137;d=Math.cos(b);const e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.qm(a));const f=e*e*d*d+d*d*d*d-d*d*c*c;if(f<0)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;const h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.rm(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.om(_.yk(g),_.yk(a))};
vE.computeOffset=function(a,b,c,d){a=_.um(a);b/=d||6378137;c=_.xk(c);var e=_.qm(a);a=_.rm(a);d=Math.cos(b);b=Math.sin(b);const f=Math.sin(e);e=Math.cos(e);const g=d*f+b*e*Math.cos(c);return new _.om(_.yk(Math.asin(g)),_.yk(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};vE.computeHeading=function(a,b){a=_.um(a);b=_.um(b);const c=_.qm(a),d=_.rm(a);a=_.qm(b);b=_.rm(b)-d;return _.rl(_.yk(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)};var Vla={encoding:_.Zv,spherical:vE,poly:uE};_.na.google.maps.geometry=Vla;_.Uk("geometry",Vla);});
